# Проверка censor pipeline на реальных логах

In [ ]:
from pathlib import Path
import sys
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

sys.path.append(str(PROJECT_ROOT))

print("PROJECT_ROOT:", PROJECT_ROOT)
print("src exists:", (PROJECT_ROOT / "src").exists())
print("reports exists:", (PROJECT_ROOT / "reports").exists())

PROJECT_ROOT: /Users/anzelikasahautdinova/censor_nlp_project
src exists: True
reports exists: True

In [46]:
LOGS_PATH = PROJECT_ROOT / "data" / "logs_to_test.csv"

In [47]:
df = pd.read_csv(LOGS_PATH, sep=";", engine="python", on_bad_lines="skip")

In [48]:
df.rename(columns={'Toxic': 'toxic'}, inplace=True)

## Предобработка текста

In [52]:
RANDOM_STATE = 42
LABEL_COL = "toxic"
TEXT_COL = "Comment"

toxic_df = df[df[LABEL_COL] == 1]
safe_df = df[df[LABEL_COL] == 0]

safe_sample = safe_df.sample(
    n=len(toxic_df),
    random_state=RANDOM_STATE
)

df = pd.concat(
    [toxic_df, safe_sample],
    axis=0
).sample(
    frac=1,
    random_state=RANDOM_STATE
).reset_index(drop=True)

print(df[LABEL_COL].value_counts())
print(df.shape)

toxic
1    308
0    308
Name: count, dtype: int64
(616, 2)

In [53]:
from src.preprocess import clean_text

df["clean_text"] = df[TEXT_COL].apply(clean_text)
df[[TEXT_COL, "clean_text"]].head()

,Comment,clean_text
0,Уроды.,уроды.
1,Самый тупорылый банк!!!!,самый тупорылый банк!!!!
2,Как пополнить счет в обход ареста,как пополнить счет в обход ареста
3,А что такое??? Почему твою мать мне не приходит код для оплаты???? Твари!!!! Где кода????? Не приходит ничего достали уже гады! Где кооооооооод????,а что такое??? почему твою мать мне не приходит код для оплаты???? твари!!!! где кода????? не приходит ничего достали уже гады! где кооооооооод????
4,Если ваша тварь мне будет звонить пойдет на х,если ваша тварь мне будет звонить пойдет на х

## Запуск Regex only

In [54]:
from src.regex_filter import RegexToxicFilter

regex_model = RegexToxicFilter()

regex_outputs = regex_model.predict_batch(df["clean_text"].tolist())

df["regex_pred"] = [x["is_toxic"] for x in regex_outputs]
df["regex_score"] = [x["score"] for x in regex_outputs]
df["regex_matches"] = [", ".join(x["matches"]) for x in regex_outputs]

df[[TEXT_COL, "regex_pred", "regex_matches"]].head(20)

,Comment,regex_pred,regex_matches
0,Уроды.,0,
1,Самый тупорылый банк!!!!,0,
2,Как пополнить счет в обход ареста,0,
3,А что такое??? Почему твою мать мне не приходит код для оплаты???? Твари!!!! Где кода????? Не приходит ничего достали уже гады! Где кооооооооод????,0,
4,Если ваша тварь мне будет звонить пойдет на х,0,
5,"Адрес этих дубиноголовых: Калининград, ул. Горького 000.",0,
6,Ты в натуре долбаеб,0,
7,У нас в городе проблема с вашими банкоматами. Где ещё можно снять наличные с кредитной карты без комиссии?,0,
8,Ваши операторы говно кроме Натальи проследите по звонкам,0,
9,"Ни в одном банке кредитку не заблокировали ни сбер ни Т банк, только в вашем ублюдском банке , в котором еще и переводом нельзя именно кредитку оплатить",0,
10,Наложено ограничение.Судебного производства нет в природе!\nВы мошенники?\nЧерез Суд с вами разбираться или Прокуратуру?\nПеревели XXXXX.\nЭто уже кража!,0,
11,Савкин жанил,0,
12,Здравствуйте. Можно ли перевести деньги из России в Украину ?,0,
13,Как отключить подтверждение в смс по переводам,0,
14,Верните деньги уроды сука,1,сука
15,Вот с этого номера звонят какие-то петухи от вашего имени +00000000000,0,
16,Альфа мани игра просто мошенническая,0,
17,Только что мне звонили с этого +00000000000 номера представились менеджерами Альфа-Банка предлагали услуги пытались выудить личную информацию,0,
18,"Добрый день! Платное годовое обслуживание не устраивает. Раньше жила на эту карту и при зарплате закрывала. Но сейчас маленький лимит, перешла на карту сбербанка. Хотела, чтобы карта Альфы лежала на всякий случай для снятия наличных без комиссии, но платить за неё ради случая, который может и не наступит, не вижу смысла",0,
19,"Ужас! Банк мошенников и крахаборов! Что мне надо сделать, чтобы закрыть эту ебучую карту?",1,ебучую

## Запуск RuBERT

In [58]:
from tqdm.auto import tqdm
from src.bert_filter import BertToxicFilter

bert_model = BertToxicFilter()

bert_outputs = []
for text in tqdm(df["clean_text"].tolist()):
    bert_outputs.append(bert_model.predict_one(text))

df["bert_pred"] = [x["is_toxic"] for x in bert_outputs]
df["bert_score"] = [x["score"] for x in bert_outputs]
df["bert_label"] = [x["label"] for x in bert_outputs]

df[[TEXT_COL, "bert_pred", "bert_label", "bert_score"]].head(20)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: sismetanin/rubert-toxic-pikabu-2ch
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  0%|          | 0/616 [00:00<?, ?it/s]

,Comment,bert_pred,bert_label,bert_score
0,Уроды.,1,LABEL_1,0.991298
1,Самый тупорылый банк!!!!,1,LABEL_1,0.994160
2,Как пополнить счет в обход ареста,0,LABEL_0,0.996592
3,А что такое??? Почему твою мать мне не приходит код для оплаты???? Твари!!!! Где кода????? Не приходит ничего достали уже гады! Где кооооооооод????,1,LABEL_1,0.878746
4,Если ваша тварь мне будет звонить пойдет на х,1,LABEL_1,0.991832
5,"Адрес этих дубиноголовых: Калининград, ул. Горького 000.",1,LABEL_1,0.980355
6,Ты в натуре долбаеб,1,LABEL_1,0.917995
7,У нас в городе проблема с вашими банкоматами. Где ещё можно снять наличные с кредитной карты без комиссии?,0,LABEL_0,0.997574
8,Ваши операторы говно кроме Натальи проследите по звонкам,0,LABEL_0,0.983151
9,"Ни в одном банке кредитку не заблокировали ни сбер ни Т банк, только в вашем ублюдском банке , в котором еще и переводом нельзя именно кредитку оплатить",0,LABEL_0,0.994767
10,Наложено ограничение.Судебного производства нет в природе!\nВы мошенники?\nЧерез Суд с вами разбираться или Прокуратуру?\nПеревели XXXXX.\nЭто уже кража!,0,LABEL_0,0.981966
11,Савкин жанил,1,LABEL_1,0.985199
12,Здравствуйте. Можно ли перевести деньги из России в Украину ?,0,LABEL_0,0.996795
13,Как отключить подтверждение в смс по переводам,0,LABEL_0,0.997056
14,Верните деньги уроды сука,1,LABEL_1,0.983585
15,Вот с этого номера звонят какие-то петухи от вашего имени +00000000000,1,LABEL_1,0.805792
16,Альфа мани игра просто мошенническая,0,LABEL_0,0.983324
17,Только что мне звонили с этого +00000000000 номера представились менеджерами Альфа-Банка предлагали услуги пытались выудить личную информацию,0,LABEL_0,0.997279
18,"Добрый день! Платное годовое обслуживание не устраивает. Раньше жила на эту карту и при зарплате закрывала. Но сейчас маленький лимит, перешла на карту сбербанка. Хотела, чтобы карта Альфы лежала на всякий случай для снятия наличных без комиссии, но платить за неё ради случая, который может и не наступит, не вижу смысла",0,LABEL_0,0.997905
19,"Ужас! Банк мошенников и крахаборов! Что мне надо сделать, чтобы закрыть эту ебучую карту?",0,LABEL_0,0.856223

## Запуск Hybrid

In [59]:
from src.hybrid_filter import HybridToxicFilter

hybrid_model = HybridToxicFilter()

hybrid_outputs = []
for text in tqdm(df["clean_text"].tolist()):
    hybrid_outputs.append(hybrid_model.predict_one(text))

df["hybrid_pred"] = [x["is_toxic"] for x in hybrid_outputs]
df["hybrid_score"] = [x["score"] for x in hybrid_outputs]
df["hybrid_matches"] = [", ".join(x.get("regex_matches", [])) for x in hybrid_outputs]

df[[TEXT_COL, "regex_pred", "bert_pred", "hybrid_pred", "regex_matches"]].head(20)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: sismetanin/rubert-toxic-pikabu-2ch
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  0%|          | 0/616 [00:00<?, ?it/s]

,Comment,regex_pred,bert_pred,hybrid_pred,regex_matches
0,Уроды.,0,1,1,
1,Самый тупорылый банк!!!!,0,1,1,
2,Как пополнить счет в обход ареста,0,0,0,
3,А что такое??? Почему твою мать мне не приходит код для оплаты???? Твари!!!! Где кода????? Не приходит ничего достали уже гады! Где кооооооооод????,0,1,1,
4,Если ваша тварь мне будет звонить пойдет на х,0,1,1,
5,"Адрес этих дубиноголовых: Калининград, ул. Горького 000.",0,1,1,
6,Ты в натуре долбаеб,0,1,1,
7,У нас в городе проблема с вашими банкоматами. Где ещё можно снять наличные с кредитной карты без комиссии?,0,0,0,
8,Ваши операторы говно кроме Натальи проследите по звонкам,0,0,0,
9,"Ни в одном банке кредитку не заблокировали ни сбер ни Т банк, только в вашем ублюдском банке , в котором еще и переводом нельзя именно кредитку оплатить",0,0,0,
10,Наложено ограничение.Судебного производства нет в природе!\nВы мошенники?\nЧерез Суд с вами разбираться или Прокуратуру?\nПеревели XXXXX.\nЭто уже кража!,0,0,0,
11,Савкин жанил,0,1,1,
12,Здравствуйте. Можно ли перевести деньги из России в Украину ?,0,0,0,
13,Как отключить подтверждение в смс по переводам,0,0,0,
14,Верните деньги уроды сука,1,1,1,сука
15,Вот с этого номера звонят какие-то петухи от вашего имени +00000000000,0,1,1,
16,Альфа мани игра просто мошенническая,0,0,0,
17,Только что мне звонили с этого +00000000000 номера представились менеджерами Альфа-Банка предлагали услуги пытались выудить личную информацию,0,0,0,
18,"Добрый день! Платное годовое обслуживание не устраивает. Раньше жила на эту карту и при зарплате закрывала. Но сейчас маленький лимит, перешла на карту сбербанка. Хотела, чтобы карта Альфы лежала на всякий случай для снятия наличных без комиссии, но платить за неё ради случая, который может и не наступит, не вижу смысла",0,0,0,
19,"Ужас! Банк мошенников и крахаборов! Что мне надо сделать, чтобы закрыть эту ебучую карту?",1,0,0,ебучую

## Сравнение моделей на логах

In [60]:
summary = pd.DataFrame({
    "model": ["Regex", "RuBERT", "Hybrid"],
    "predicted_toxic_count": [
        int(df["regex_pred"].sum()),
        int(df["bert_pred"].sum()),
        int(df["hybrid_pred"].sum()),
    ],
    "predicted_toxic_share": [
        df["regex_pred"].mean(),
        df["bert_pred"].mean(),
        df["hybrid_pred"].mean(),
    ]
})

summary

    model  predicted_toxic_count  predicted_toxic_share
0   Regex                     85               0.137987
1  RuBERT                    313               0.508117
2  Hybrid                    313               0.508117

In [62]:
df

,Comment,toxic,clean_text,regex_pred,regex_score,regex_matches,hybrid_pred,hybrid_score,hybrid_matches,bert_pred,bert_score,bert_label
0,Уроды.,1,уроды.,0,0.0,,1,0.991298,,1,0.991298,LABEL_1
1,Самый тупорылый банк!!!!,1,самый тупорылый банк!!!!,0,0.0,,1,0.994160,,1,0.994160,LABEL_1
2,Как пополнить счет в обход ареста,0,как пополнить счет в обход ареста,0,0.0,,0,0.003408,,0,0.996592,LABEL_0
3,А что такое??? Почему твою мать мне не приходит код для оплаты???? Твари!!!! Где кода????? Не приходит ничего достали уже гады! Где кооооооооод????,1,а что такое??? почему твою мать мне не приходит код для оплаты???? твари!!!! где кода????? не приходит ничего достали уже гады! где кооооооооод????,0,0.0,,1,0.878746,,1,0.878746,LABEL_1
4,Если ваша тварь мне будет звонить пойдет на х,1,если ваша тварь мне будет звонить пойдет на х,0,0.0,,1,0.991832,,1,0.991832,LABEL_1
...,...,...,...,...,...,...,...,...,...,...,...,...
611,Ты долбаеб,1,ты долбаеб,0,0.0,,1,0.959336,,1,0.959336,LABEL_1
612,Пиздец ты ебан,1,пиздец ты ебан,1,1.0,"пиздец, ебан, пиздец",1,1.000000,"пиздец, ебан, пиздец",1,0.966517,LABEL_1
613,"Вчера вы писали, что вопрос решится в течении суток!!! Верните деньги, мошенники!!!",1,"вчера вы писали, что вопрос решится в течении суток!!! верните деньги, мошенники!!!",0,0.0,,0,0.071744,,0,0.928256,LABEL_0
614,Не тупой бот,0,не тупой бот,0,0.0,,1,0.982859,,1,0.982859,LABEL_1
615,Шавки хуйла,1,шавки хуйла,0,0.0,,1,0.993219,,1,0.993219,LABEL_1

In [66]:
error_examples = df[
    (
        (df["regex_pred"] != df["toxic"]) |
        (df["bert_pred"] != df["toxic"])
    )
][[
    "clean_text",
    "toxic",
    "regex_pred",
    "bert_pred",
    "hybrid_pred"
]].head(70)

error_examples

,clean_text,toxic,regex_pred,bert_pred,hybrid_pred
0,уроды.,1,0,1,1
1,самый тупорылый банк!!!!,1,0,1,1
3,а что такое??? почему твою мать мне не приходит код для оплаты???? твари!!!! где кода????? не приходит ничего достали уже гады! где кооооооооод????,1,0,1,1
4,если ваша тварь мне будет звонить пойдет на х,1,0,1,1
5,"адрес этих дубиноголовых: калининград, ул. горького 000.",1,0,1,1
...,...,...,...,...,...
138,вы цыгане !,1,0,1,1
140,где мои деньги машенники,1,0,0,0
141,вот это что? где мои деньги?!?!? на этом счету нету денег!!!!!!! воры,1,0,0,0
143,вы дебилы. я ее закрыл в январе. прочитайте выше переписку,1,0,1,1
144,чужому человеку,0,0,1,1

In [67]:
LABEL_COL = "toxic"

if LABEL_COL in df.columns:
    from src.evaluate import evaluate_predictions
    
    y_true = df[LABEL_COL].astype(int)
    
    metrics = []
    metrics.append(evaluate_predictions(y_true, df["regex_pred"], "Regex logs"))
    metrics.append(evaluate_predictions(y_true, df["bert_pred"], "RuBERT logs"))
    metrics.append(evaluate_predictions(y_true, df["hybrid_pred"], "Hybrid logs"))
    
    metrics_df = pd.DataFrame(metrics)
    display(metrics_df)

===== Regex logs =====
{'model': 'Regex logs', 'accuracy': 0.6217532467532467, 'precision': 0.9411764705882353, 'recall': 0.2597402597402597, 'f1': 0.4071246819338422}

Classification report:
              precision    recall  f1-score   support

           0       0.57      0.98      0.72       308
           1       0.94      0.26      0.41       308

    accuracy                           0.62       616
   macro avg       0.76      0.62      0.56       616
weighted avg       0.76      0.62      0.56       616


Confusion matrix:
[[303   5]
 [228  80]]

===== RuBERT logs =====
{'model': 'RuBERT logs', 'accuracy': 0.797077922077922, 'precision': 0.792332268370607, 'recall': 0.8051948051948052, 'f1': 0.7987117552334944}

Classification report:
              precision    recall  f1-score   support

           0       0.80      0.79      0.80       308
           1       0.79      0.81      0.80       308

    accuracy                           0.80       616
   macro avg       0.80      0.80      0.80       616
weighted avg       0.80      0.80      0.80       616


Confusion matrix:
[[243  65]
 [ 60 248]]

===== Hybrid logs =====
{'model': 'Hybrid logs', 'accuracy': 0.797077922077922, 'precision': 0.792332268370607, 'recall': 0.8051948051948052, 'f1': 0.7987117552334944}

Classification report:
              precision    recall  f1-score   support

           0       0.80      0.79      0.80       308
           1       0.79      0.81      0.80       308

    accuracy                           0.80       616
   macro avg       0.80      0.80      0.80       616
weighted avg       0.80      0.80      0.80       616


Confusion matrix:
[[243  65]
 [ 60 248]]

         model  accuracy  precision    recall        f1
0   Regex logs  0.621753   0.941176  0.259740  0.407125
1  RuBERT logs  0.797078   0.792332  0.805195  0.798712
2  Hybrid logs  0.797078   0.792332  0.805195  0.798712

In [26]:
df["bert_score"].describe()

count    3001.000000
mean        0.950721
std         0.097334
min         0.503790
25%         0.966137
50%         0.993329
75%         0.996897
max         0.998248
Name: bert_score, dtype: float64

## Анализ расхождений Regex и BERT

In [35]:
regex_only_toxic = df[
    (df["regex_pred"] == 1) &
    (df["bert_pred"] == 0)
].copy()

bert_only_toxic = df[
    (df["regex_pred"] == 0) &
    (df["bert_pred"] == 1)
].copy()

both_toxic = df[
    (df["regex_pred"] == 1) &
    (df["bert_pred"] == 1)
].copy()

print("Regex toxic, BERT safe:", len(regex_only_toxic))
print("Regex safe, BERT toxic:", len(bert_only_toxic))
print("Both toxic:", len(both_toxic))

Regex toxic, BERT safe: 8
Regex safe, BERT toxic: 236
Both toxic: 77

In [45]:
regex_only_toxic[[TEXT_COL, "regex_matches", "bert_label", "bert_score"]].head(100)

,comment,regex_matches,bert_label,bert_score
118,"Вчера было 170 рублей ,проценты за кредитку,и так же вчера положил на счёт кредитки энную сумму денег,а сегодня проценты выросли,??? Это что за такое? Они должны наоборот уменьшиться,что за сука пидарский банк ваш ?",сука,LABEL_0,0.997788
162,Как связаться с человеком блять,блять,LABEL_0,0.963245
176,"Я не могу оплатить кредиты я из Курска. Думаю вы это должны знать гандоны. Я не разу не на минуту не просрочил платежи, в этот раз я вынужден",гандоны,LABEL_0,0.997994
198,"Ужас! Банк мошенников и крахаборов! Что мне надо сделать, чтобы закрыть эту ебучую карту?",ебучую,LABEL_0,0.856223
271,"Куръер конечно, полная мразь, он мне сразу не понравился, алкаш, да и банк, конечно говно полное, наебшики ебаные, да, Марин, конечно, отключаем эту хуету, я много раз операторов спрашивал, если ли платежи, не одна шкура мне не подсказала..","ебаные, мразь",LABEL_0,0.997479
305,Оформлю банкротство и пошли на хуй тогда. Раз Я должен пробиваться к оператору,"хуй, хуй",LABEL_0,0.997554
486,Уважение... Да пипец одна на ебало во. Вчера была возможность в приложении запросить рефинансирование без посещения банка а сегодня нет. Человек который должен был настроить приложение для айфона не приехал во время папе придется еще один день в этом сарае в рязани.,ебало,LABEL_0,0.998179
566,Я у вас спросил что ? Чтоб вы мне рассказали если я сниму наличные и что будет ? Мне какая разница при снятии наличных какой процент изымут там нечего нового все так же а вы мне объясните какой процент потом будет ? Или вы настолько глупая или я хуй знает где вас таки набирают походу по объявлению,"хуй, хуй",LABEL_0,0.862802

In [38]:
pd.set_option('display.max_colwidth', None)  # Or pd.options.display.max_colwidth = None

In [43]:
bert_only_toxic[[TEXT_COL, "bert_label", "bert_score"]].head(50)

,comment,bert_label,bert_score
0,"Я ничего не должен, уйобки. \nРасторгните договор, твари.",LABEL_1,0.987963
1,Опять суки деньги прокручиваете,LABEL_1,0.977816
5,Вы что идиоты?),LABEL_1,0.986459
8,Когда нибудь ваш гребанный баек будет еормально работать? Вымогатели,LABEL_1,0.996025
9,Вы наебалово. Игры ваши гейские,LABEL_1,0.993842
14,"Уроды вы, списываете хорошо, при этом нигде нет информации про такие моменты!!!",LABEL_1,0.865267
15,Дрявый банк,LABEL_1,0.854482
16,Альфа-Помощник ты бесполезен!,LABEL_1,0.908899
18,Мошенники представляются вами,LABEL_1,0.548768
19,боже альфа банк самый дерьмовый банк на пару со сбером,LABEL_1,0.856843
21,ой идите нахуй,LABEL_1,0.972228
26,Мудила,LABEL_1,0.992166
29,Запихните себе кэшбэк крохоборы,LABEL_1,0.625761
36,Что за бред вы предлагаете,LABEL_1,0.896434
37,ВОРЫ!!!!!,LABEL_1,0.917523
38,Любимая чмоня,LABEL_1,0.992606
41,У вас люди живые есть? Какой смысл переписываться с наитупейшим роботом,LABEL_1,0.981038
47,Жопа а не банк,LABEL_1,0.720426
50,Да вы конечно пидорасы усложняющие жизнь,LABEL_1,0.988703
51,"0 баллов вам, пидарасы",LABEL_1,0.966137
54,Какие опять нахуй переводы суки за что снимаете день ги,LABEL_1,0.990549
56,Господи какой дебильный банк я не могу,LABEL_1,0.695855
58,Заебал!!! Бот гребаный. Позови оператора,LABEL_1,0.983467
62,Я зайду в банк и закрою карточки и не надейтесь жулики!!!,LABEL_1,0.942010
65,Да пошли вы нахуй с таким кэшбэком!,LABEL_1,0.912955
70,Вы че дибилы,LABEL_1,0.968998
73,Вы или дибилы или подонки или и то и другое вместе как говорил наш Президент.,LABEL_1,0.991994
75,"Я с вам пытался, честно пытался вести диалог как внятной, большой и сильной компанией, а вы ни за что ни про что заблокировали карту, два похода в отделение укрепили мое мнение о вас! Вы вымогатели, местами воры и дилетанты! Чеки им неси из магазина, за три месяца........",LABEL_1,0.964775
77,Так вы вообще идиоты,LABEL_1,0.983287
82,Охуевшие,LABEL_1,0.989165
84,Идите нах,LABEL_1,0.957473
88,Говна кусок никто не писал что надо идти в банк тупая дура,LABEL_1,0.988109
89,Вы о чём ???Что вы голову морочите !!!??? Я только что закрыл альфа счёт и вывожу деньги из вашего поганого банка !!! Вы меня на альфа счёте киданули !!!,LABEL_1,0.957087
93,Идите нахуй в общем,LABEL_1,0.986031
96,"Ворюги, где деньги?",LABEL_1,0.974628
97,Ты че тупой,LABEL_1,0.957650
99,Ты в натуре долбаеб,LABEL_1,0.917995
101,Отибитесь,LABEL_1,0.708665
102,Вы дебилы ? Я не умею разговаривать?!!!? Я немая !!!! Инвалид,LABEL_1,0.991181
106,Пашол ты. Нахуй урод,LABEL_1,0.980521
108,пошел на хууй,LABEL_1,0.992519
110,Я же говорю дебилы,LABEL_1,0.994757
111,Меня напрягает нежелательная однерка.\nЯ Заебался смотреть ваши предложения кредитных карт. Избавте меня от этого дискомфорта или я перейду в Сбер....,LABEL_1,0.939849
115,Вы чё пидоры по 00 часов отвечаете,LABEL_1,0.985380
117,Блин ну Уберите этого тупорылого киборга блин вы б**** альфа-банк в натуре а это он тупой б**** он н**** не понимает когда нужно связь с оператором Ну н**** связать не может это тупорылая роботина блин а обучена она определённые задачи и всё можете его убрать,LABEL_1,0.989619
122,"Пожалуйста, нахуй иди",LABEL_1,0.919342
124,Нахуй ваша помощь не нужна клоуны,LABEL_1,0.973648
126,В жопу иди,LABEL_1,0.979027
127,Ты долбаеб,LABEL_1,0.959336
129,"Альфа- Банк совсем тупой.\n\nВот:00 мар. 0000, 00:00\nКОМУ\nПАПКА:\nВходящие\nЗдравствуйте, Елена Владимировна.\n\nМы уже возмещали комиссию по обращению № XXXXX дополнительного возмещения не предусмотрено.\n\nОНИ ВОЗМЕСТИЛИ КОМИССИЮ И ТУТ ЖЕ СПИСАЛИ ОПЯТЬ И ХОТЯТ ЕЩЁ, И ТАК ПО КРУГУ.\n\nАльфа-Банк \n\nКороче. Альфа банк плохой.\n В первой половине прошлого года через суд они удержали с меня наконец то появившуюся пенсию ( на 0, 0 ковидных года её отсрочило повышение пенс возраста). Около 00 т.р. Мой долг.\nЕщё в 0000 я заблокировала карту.\nПочти 0 мес они звонили мне до 00 раз в день, мол, я должна по кредиту. Я отправила им 0000. Якобы мой непонятный долг. И я опять должна. Они сами говорят : это комиссия, а не кредит, но система этого не понимает, не могут решить эту техническую задачу.",LABEL_1,0.880561

## 10. Сохранение результатов

In [ ]:
reports_dir = PROJECT_ROOT / "reports"
reports_dir.mkdir(exist_ok=True)

logs_df.to_csv(reports_dir / "logs_pipeline_predictions.csv", index=False)
regex_only_toxic.to_csv(reports_dir / "logs_regex_only_toxic.csv", index=False)
bert_only_toxic.to_csv(reports_dir / "logs_bert_only_toxic.csv", index=False)
both_toxic.to_csv(reports_dir / "logs_both_toxic.csv", index=False)

print("Saved:")
print(reports_dir / "logs_pipeline_predictions.csv")
print(reports_dir / "logs_regex_only_toxic.csv")
print(reports_dir / "logs_bert_only_toxic.csv")
print(reports_dir / "logs_both_toxic.csv")